const ACCESS_EXP = '15m';
const REFRESH_EXP = '1d';
const REFRESH_EXP_MS = 24 * 60 * 60 * 1000;

const LOGIN_FAIL_THRESHOLD = 5;
const LOGIN_BACKOFF_BASE_MS = 15 * 1000;
const LOGIN_BACKOFF_MAX_MS = 15 * 60 * 1000;

module.exports = {
  ACCESS_EXP,
  REFRESH_EXP,
  REFRESH_EXP_MS,
  LOGIN_FAIL_THRESHOLD,
  LOGIN_BACKOFF_BASE_MS,
  LOGIN_BACKOFF_MAX_MS
};
